import { registerRootComponent } from 'expo'

import { installExternalNetworkGuard } from './externalNetworkGuard'
import { registerStorybookRoot } from './storybookRoot'

// This guard must precede generated story imports and remains active across
// Storybook navigation; preview decorators only provide presentation context.
installExternalNetworkGuard()

// Generated by Storybook's Metro wrapper when STORYBOOK_ENABLED is exactly true.
// Do not make this a static import: disabled Expo Router bundles must exclude it.
const { view } = require('./storybook.requires')

console.info('RALLY_STORYBOOK_SENTINEL')

export default registerStorybookRoot(view, registerRootComponent as (root: unknown) => void)
