import { StyleSheet } from 'react-native'

import { Radius, Spacing, type SportPalette } from '@/constants/theme'

export function createArenaSessionLiveCourtStyles(theme: SportPalette) {
  return StyleSheet.create({
    section: {
      borderRadius: Radius.xxl,
      backgroundColor: theme.fightPanel,
      padding: Spacing.md,
      gap: 12,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.18,
      shadowRadius: 18,
      elevation: 5,
    },
    headingRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    eyebrow: { color: theme.trust, fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
    title: { color: theme.fightInk, fontSize: 19, lineHeight: 24, fontWeight: '900', marginTop: 2 },
    liveBadge: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: Radius.pill, backgroundColor: theme.trustSoft, paddingHorizontal: 10 },
    liveDot: { width: 7, height: 7, borderRadius: Radius.pill, backgroundColor: theme.trust },
    liveText: { color: theme.trust, fontSize: 10, fontWeight: '900', letterSpacing: 0.8 },
    scoreVault: { minHeight: 108, borderRadius: Radius.xl, borderWidth: 1, borderColor: theme.fightLine, backgroundColor: theme.fightBg, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12 },
    scoreTeam: { flex: 1, alignItems: 'center', gap: 4 },
    scoreNameRow: { maxWidth: '100%', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4 },
    scoreTeamName: { maxWidth: 112, color: theme.fightInkSoft, fontSize: 11, fontWeight: '900' },
    score: { fontSize: 38, lineHeight: 42, fontWeight: '900', fontVariant: ['tabular-nums'] },
    scoreCenter: { width: 64, alignItems: 'center', gap: 7 },
    scoreDivider: { color: theme.fightInk, fontSize: 26, fontWeight: '700' },
    clockChip: { minHeight: 25, borderRadius: Radius.pill, backgroundColor: theme.fightPanel, flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 7 },
    clockText: { color: theme.fightInk, fontSize: 10, fontWeight: '900', fontVariant: ['tabular-nums'] },
    matchMeta: { minHeight: 32, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
    matchStatus: { color: theme.fightInkSoft, fontSize: 12, fontWeight: '800' },
    kingBadge: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end', alignItems: 'center', gap: 5 },
    kingLabel: { maxWidth: 140, color: theme.economy, fontSize: 11, fontWeight: '900' },
    court: { position: 'relative', height: 420, overflow: 'hidden', borderRadius: Radius.xl, backgroundColor: theme.fightBg },
    previewCourt: { height: 250, overflow: 'hidden', borderRadius: Radius.xxl, backgroundColor: theme.fightBg },
    previewShade: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(22,22,22,0.12)' },
    marker: { position: 'absolute', width: 92, alignItems: 'center', transform: [{ translateX: -46 }, { translateY: -22 }] },
    markerRing: { width: 44, height: 44, borderRadius: Radius.pill, borderWidth: 3, backgroundColor: theme.fightPanel, padding: 2 },
    markerDot: { flex: 1, borderRadius: Radius.pill, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' },
    markerImage: { width: '100%', height: '100%' },
    markerInitial: { fontSize: 11, fontWeight: '900' },
    markerCaption: { maxWidth: 92, alignItems: 'center', borderRadius: Radius.pill, backgroundColor: 'rgba(22,22,22,0.82)', paddingHorizontal: 7, paddingVertical: 3, marginTop: 3 },
    markerName: { color: theme.fightInk, fontSize: 9, fontWeight: '900' },
    markerPosition: { color: theme.fightInkSoft, fontSize: 8, fontWeight: '800' },
    teamSummary: { borderRadius: Radius.lg, backgroundColor: theme.fightBg, paddingHorizontal: 12, paddingVertical: 4 },
    summaryTeam: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 9 },
    summaryDivider: { height: StyleSheet.hairlineWidth, backgroundColor: theme.fightLine },
    summaryDot: { width: 9, height: 9, borderRadius: Radius.pill },
    summaryCopy: { flex: 1, minWidth: 0 },
    summaryName: { color: theme.fightInk, fontSize: 12, fontWeight: '900' },
    summaryMembers: { color: theme.fightInkSoft, fontSize: 10, fontWeight: '700', marginTop: 2 },
  })
}
