import { StyleSheet } from 'react-native'
import { Fonts, Radius, Spacing, type SportPalette } from '@/constants/theme'

export function createRefereePassScreenStyles(theme: SportPalette) {
  return StyleSheet.create({
    container: { alignItems: 'center', paddingHorizontal: Spacing.lg, gap: Spacing.lg },
    block: { width: '100%', maxWidth: 420, alignSelf: 'center', gap: Spacing.sm },
    topBar: { width: '100%', minHeight: 52, alignItems: 'center', justifyContent: 'center' },
    topBarBack: { position: 'absolute', left: 0, top: 4 },
    topBarCopy: { alignItems: 'center' },
    title: {
      color: theme.ink,
      fontSize: 20,
      lineHeight: 29,
      fontWeight: '900',
      fontFamily: Fonts?.thaiHead,
      textAlign: 'center',
    },
    kicker: {
      color: theme.orange,
      fontSize: 9,
      lineHeight: 13,
      fontWeight: '900',
      letterSpacing: 1.1,
      textTransform: 'uppercase',
    },
    panel: {
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.surface,
      padding: Spacing.md,
      gap: Spacing.sm,
    },
    statusCard: {
      minHeight: 116,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.surface,
      padding: Spacing.md,
      boxShadow: theme.shadowSoft,
    },
    sportIcon: {
      width: 48,
      height: 48,
      borderRadius: Radius.lg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusCopy: { flex: 1, minWidth: 0 },
    statusIdentityRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: Spacing.sm,
    },
    sportLabel: {
      color: theme.muted,
      fontSize: 11,
      lineHeight: 17,
      fontWeight: '800',
      fontFamily: Fonts?.thaiMedium,
    },
    statusTitle: {
      flexShrink: 1,
      color: theme.ink,
      fontSize: 17,
      lineHeight: 25,
      fontWeight: '900',
      fontFamily: Fonts?.thaiHead,
    },
    statusLevel: {
      flexShrink: 0,
      color: theme.muted,
      fontSize: 11,
      lineHeight: 17,
      fontWeight: '900',
      fontFamily: Fonts?.rounded,
      fontVariant: ['tabular-nums'],
    },
    statusTier: {
      color: theme.muted,
      fontSize: 11,
      lineHeight: 17,
      fontWeight: '700',
      fontFamily: Fonts?.thaiBody,
    },
    statusBody: {
      color: theme.inkSoft,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '700',
      fontFamily: Fonts?.thaiBody,
    },
    expandHint: {
      marginTop: 2,
      color: theme.orange,
      fontSize: 10,
      lineHeight: 15,
      fontWeight: '800',
      fontFamily: Fonts?.thaiMedium,
    },
    applyButton: { marginTop: Spacing.xs },
    applyBusy: { minHeight: 52, alignItems: 'center', justifyContent: 'center' },
    detailsStack: { width: '100%', alignItems: 'center', gap: Spacing.lg },
    sectionTitle: {
      color: theme.ink,
      fontSize: 16,
      lineHeight: 24,
      fontWeight: '900',
      fontFamily: Fonts?.thaiHead,
    },
    conditionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      paddingVertical: Spacing.xs,
    },
    conditionDivider: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.line,
      paddingTop: Spacing.sm,
    },
    conditionText: {
      flex: 1,
      color: theme.ink,
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '700',
      fontFamily: Fonts?.thaiBody,
    },
    noteCard: {
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.surface,
      padding: Spacing.md,
    },
  })
}
