import { Platform, StyleSheet } from 'react-native'
import { OnAccent, Radius, Spacing, type SportPalette } from '@/constants/theme'

export function matchDetailStyles(theme: SportPalette) {
  return StyleSheet.create({
    container: { padding: Spacing.xl, paddingBottom: 48, gap: Spacing.md, backgroundColor: theme.bg },
    basketballLobbyScreen: {
      flex: 1,
      backgroundColor: theme.bg,
    },
    basketballLobbyDarkScrim: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(18,18,18,0.38)',
    },
    basketballLobbyScroll: {
      flex: 1,
    },
    basketballLobbyContainer: {
      minHeight: '100%',
      paddingHorizontal: 0,
      paddingTop: 18,
      paddingBottom: 16,
      gap: Spacing.sm,
      backgroundColor: 'transparent',
    },
    finalBackButton: {
      marginLeft: Spacing.md,
      marginBottom: Spacing.sm,
    },
    basketballStakeOverlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 18,
      backgroundColor: 'rgba(22,22,22,0.66)',
    },
    basketballStakeScrim: {
      ...StyleSheet.absoluteFillObject,
    },
    basketballStakeSheet: {
      width: '100%',
      maxWidth: 390,
      maxHeight: '88%',
    },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: Spacing.xl, backgroundColor: theme.bg },
    loadErrorState: { width: '100%', maxWidth: 320, alignItems: 'center', gap: Spacing.sm },
    loadErrorIcon: {
      width: 56,
      height: 56,
      borderRadius: Radius.xl,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.riskSoft,
    },
    loadErrorHint: { color: theme.muted, fontSize: 14, lineHeight: 20, fontWeight: '700', textAlign: 'center' },
    loadErrorPrimary: {
      width: '100%',
      minHeight: 52,
      borderRadius: Radius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: Spacing.sm,
      backgroundColor: theme.orange,
      marginTop: Spacing.sm,
    },
    loadErrorPrimaryText: { color: OnAccent.onLight, fontSize: 15, fontWeight: '900' },
    headerRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.md, marginBottom: Spacing.sm },
    activity: {
      fontSize: 28,
      fontWeight: '900',
      color: theme.ink,
      textTransform: 'capitalize',
      letterSpacing: -0.5,
    },
    teamLabel: {
      fontSize: 13,
      fontWeight: '800',
      color: theme.muted,
      letterSpacing: 1.2,
      marginTop: 2,
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: Spacing.sm,
      marginTop: Spacing.xs,
    },
    metaPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 5,
      backgroundColor: theme.surface,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: theme.line,
    },
    metaPillText: { fontSize: 12, color: theme.inkSoft, letterSpacing: 0.3 },
    codePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 7,
      backgroundColor: theme.amberSoft,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,178,61,0.35)',
    },
    codePillText: {
      fontSize: 13,
      fontWeight: '900' as const,
      color: theme.amber,
      letterSpacing: 2,
      fontVariant: ['tabular-nums'] as const,
    },
    potCard: {
      marginTop: Spacing.md,
      backgroundColor: theme.surface,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: theme.line,
      padding: Spacing.lg,
      alignItems: 'center',
      gap: 4,
      ...Platform.select({
        web: { boxShadow: '0 0 40px rgba(255,77,61,0.18)' },
        default: {
          shadowColor: theme.red,
          shadowOffset: { width: 0, height: 0 },
          shadowOpacity: 0.25,
          shadowRadius: 18,
          elevation: 4,
        },
      }),
    },
    potLabel: {
      fontSize: 11,
      color: theme.muted,
      letterSpacing: 2,
      fontWeight: '800',
    },
    potValue: {
      fontSize: 56,
      fontWeight: '900',
      color: theme.ink,
      letterSpacing: -1,
      fontVariant: ['tabular-nums'],
      lineHeight: 62,
    },
    potUnit: { fontSize: 13, color: theme.muted, letterSpacing: 1, fontWeight: '700' },
    rule: {
      fontSize: 13,
      color: theme.inkSoft,
      marginTop: Spacing.sm,
      fontStyle: 'italic',
      lineHeight: 20,
    },
    codeBox: {
      marginTop: Spacing.md,
      backgroundColor: theme.amberSoft,
      borderRadius: Radius.lg,
      padding: Spacing.md,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: 'rgba(255,178,61,0.28)',
    },
    codeLabel: { fontSize: 10, color: theme.amber, fontWeight: '800', letterSpacing: 1.5 },
    code: {
      fontSize: 18,
      fontWeight: '900',
      letterSpacing: 3,
      marginTop: 4,
      color: theme.ink,
      fontVariant: ['tabular-nums'],
    },
    codeActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
      marginTop: Spacing.md,
    },
    codeButton: {
      minWidth: 88,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: 'rgba(255,178,61,0.34)',
      borderRadius: Radius.md,
      paddingHorizontal: 12,
      paddingVertical: 9,
      backgroundColor: theme.surface,
    },
    codeButtonText: { color: theme.amber, fontSize: 12, fontWeight: '800', letterSpacing: 0.3 },
    divider: { height: 1, backgroundColor: theme.line, marginVertical: Spacing.md },
    info: {
      fontSize: 13,
      color: theme.muted,
      marginBottom: Spacing.sm,
      textAlign: 'center',
      letterSpacing: 0.3,
    },
    progressTrack: {
      height: 4,
      backgroundColor: theme.surface,
      borderRadius: 2,
      overflow: 'hidden',
      marginTop: Spacing.sm,
    },
    progressFill: { height: 4, backgroundColor: theme.green, borderRadius: 2 },
    acceptBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 7,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(255,77,61,0.4)',
      backgroundColor: theme.redSoft,
    },
    acceptBadgeAccepted: {
      borderColor: 'rgba(50,213,131,0.4)',
      backgroundColor: theme.greenSoft,
    },
    acceptBadgeText: {
      fontSize: 13,
      fontWeight: '900' as const,
      color: theme.red,
      letterSpacing: 0.5,
      fontVariant: ['tabular-nums'] as const,
    },
    acceptBadgeTextAccepted: { color: theme.greenVivid },
    acceptBadgePressed: {
      backgroundColor: theme.greenSoft,
      borderColor: 'rgba(50,213,131,0.5)',
    },
    acceptBadgePressedAccepted: {
      backgroundColor: theme.redSoft,
      borderColor: 'rgba(255,77,61,0.5)',
    },
    startButton: {
      backgroundColor: theme.orange,
      gap: 4,
      ...Platform.select({
        web: { boxShadow: `0 10px 28px ${theme.orange}47` },
        default: {
          shadowColor: theme.orange,
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.3,
          shadowRadius: 14,
          elevation: 4,
        },
      }),
    },
    startButtonDisabled: {
      backgroundColor: theme.surfaceStrong,
      shadowOpacity: 0,
      elevation: 0,
    },
    startButtonHint: {
      fontSize: 11,
      color: theme.mutedSoft,
      letterSpacing: 0.3,
      fontWeight: '600' as const,
    },
    button: {
      backgroundColor: theme.red,
      borderRadius: Radius.lg,
      padding: 16,
      alignItems: 'center',
      marginTop: Spacing.sm,
    },
    buttonText: { color: theme.chalk, fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
    buttonAccepted: {
      backgroundColor: theme.greenSoft,
      borderWidth: 1,
      borderColor: 'rgba(50,213,131,0.3)',
    },
    buttonAcceptedText: { color: theme.greenVivid, fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
    secondaryButton: {
      borderWidth: 1,
      borderColor: theme.line,
      borderRadius: Radius.lg,
      padding: 16,
      alignItems: 'center',
      marginTop: Spacing.sm,
    },
    secondaryButtonText: { color: theme.inkSoft, fontSize: 15, fontWeight: '700', letterSpacing: 0.3 },
    result: { alignItems: 'center', padding: Spacing.xl, gap: Spacing.md },
    resultText: { fontSize: 22, fontWeight: '900', color: theme.ink, letterSpacing: -0.5 },
  })
}
