import { StyleSheet } from 'react-native'
import {
  Arcade,
  Fonts,
  Radius,
  RunArenaPalette,
  Spacing,
  type RunArenaPalette as RunArenaColors,
  type SportPalette,
} from '@/constants/theme'
import type { AppLanguage } from '@/lib/i18n/language'

export function newMatchStyles(theme: SportPalette) {
  return StyleSheet.create({
  container: { padding: Spacing.xl, paddingBottom: 48, gap: Spacing.sm, backgroundColor: theme.bg },
  soloRunCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.lg,
    borderRadius: Radius.xl,
    borderWidth: 1,
    borderColor: 'rgba(255,77,61,0.32)',
    backgroundColor: theme.redSoft,
    marginTop: Spacing.sm,
  },
  soloRunIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,77,61,0.18)',
  },
  soloRunTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: theme.ink,
  },
  soloRunHint: {
    fontSize: 12,
    color: theme.inkSoft,
    lineHeight: 17,
    marginTop: 2,
  },
  label: {
    fontSize: 11,
    fontWeight: '800',
    color: theme.muted,
    marginTop: Spacing.md,
    letterSpacing: 1.4,
    textTransform: 'uppercase',
  },
  hint: { fontSize: 12, color: theme.mutedSoft, marginTop: 4 },
  pills: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginVertical: Spacing.xs },
  optionRow: { flexDirection: 'row', gap: Spacing.sm, marginVertical: Spacing.xs },
  optionPill: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  optionStack: { gap: Spacing.sm, marginVertical: Spacing.xs },
  optionCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: Radius.lg,
    padding: Spacing.md,
    backgroundColor: theme.surface,
  },
  optionCardActive: {
    backgroundColor: theme.redSoft,
    borderColor: 'rgba(255,77,61,0.45)',
  },
  optionTitle: { fontSize: 14, color: theme.ink, fontWeight: '900', letterSpacing: 0 },
  optionHint: { fontSize: 12, color: theme.muted, lineHeight: 17, marginTop: 2 },
  optionMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 7 },
  optionMetaPill: {
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: Radius.pill,
    backgroundColor: theme.surfaceStrong,
    color: theme.inkSoft,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
  },
  modeHint: {
    fontSize: 12,
    color: theme.muted,
    lineHeight: 16,
    marginTop: Spacing.xs,
    paddingHorizontal: 2,
  },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: Radius.pill,
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: theme.surface,
  },
  pillActive: {
    backgroundColor: theme.redSoft,
    borderColor: 'rgba(255,77,61,0.45)',
  },
  pillText: { fontSize: 13, color: theme.inkSoft, fontWeight: '700', letterSpacing: 0.3 },
  optionPillText: { flexShrink: 1, minWidth: 0 },
  pillTextActive: { color: theme.red },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginVertical: Spacing.xs,
  },
  stepperButton: {
    width: 44,
    height: 44,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,77,61,0.45)',
    backgroundColor: theme.redSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonDisabled: {
    opacity: 0.45,
    borderColor: theme.line,
    backgroundColor: theme.surface,
  },
  stepperValue: {
    flex: 1,
    minHeight: 44,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: theme.line,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperNumber: {
    fontSize: 22,
    fontWeight: '900',
    color: theme.ink,
    fontVariant: ['tabular-nums'],
    lineHeight: 26,
  },
  stepperLabel: { fontSize: 10, fontWeight: '800', color: theme.muted, letterSpacing: 1 },
  input: {
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: Radius.lg,
    padding: 14,
    fontSize: 15,
    color: theme.ink,
    backgroundColor: theme.surface,
  },
  codeInput: { letterSpacing: 6, fontWeight: '900', textAlign: 'center', marginTop: Spacing.sm },

  // Lobby
  lobbyRow: { flexDirection: 'row', gap: Spacing.sm, marginVertical: Spacing.xs },
  lobbyChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 11,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: theme.line,
    backgroundColor: theme.surface,
  },
  lobbyChipActive: { backgroundColor: theme.redSoft, borderColor: 'rgba(255,77,61,0.45)' },
  lobbyChipText: { fontSize: 14, fontWeight: '800', color: theme.muted },
  lockRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 11,
    paddingHorizontal: 14,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: theme.line,
    backgroundColor: theme.surface,
    marginTop: Spacing.sm,
  },
  lockRowActive: { borderColor: 'rgba(245,166,35,0.45)', backgroundColor: theme.amberSoft },
  lockRowText: { flex: 1, fontSize: 13, fontWeight: '700', color: theme.mutedSoft },
  // Thai label (เปิดให้ดูสด) — no fontWeight/lineHeight, see usage site.
  spectateRowText: { flex: 1, fontSize: 13, color: theme.mutedSoft },

  // Stake combined card
  stakeCard: {
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: Radius.lg,
    backgroundColor: theme.surface,
    padding: Spacing.md,
    gap: Spacing.sm,
    marginVertical: Spacing.xs,
  },
  stakeRow: { flexDirection: 'row', gap: Spacing.sm },
  stakeAmountInput: { backgroundColor: theme.bgElevated },
  stakeUnit: { fontSize: 11, color: theme.mutedSoft, fontWeight: '700', letterSpacing: 0.3 },
  inviteeRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: Spacing.sm },
  sideBadge: {
    fontSize: 10,
    fontWeight: '900',
    color: theme.inkSoft,
    backgroundColor: theme.surfaceStrong,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: Radius.sm,
    minWidth: 64,
    textAlign: 'center',
    letterSpacing: 1.2,
  },
  inviteePicker: {
    flex: 1,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: Radius.lg,
    paddingHorizontal: 14,
    backgroundColor: theme.surface,
  },
  inviteePickerActive: {
    borderColor: 'rgba(255,77,61,0.45)',
    backgroundColor: theme.redSoft,
  },
  inviteePickerText: { flex: 1, fontSize: 14, color: theme.muted, fontWeight: '700' },
  inviteePickerTextActive: { color: theme.red },
  clearInviteeButton: {
    width: 40,
    height: 40,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: theme.line,
    backgroundColor: theme.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {
    backgroundColor: theme.red,
    borderRadius: Radius.lg,
    padding: 16,
    alignItems: 'center',
    marginTop: Spacing.xl,
  },
  buttonText: { color: theme.chalk, fontSize: 15, fontWeight: '800', letterSpacing: 0.5 },
  secondaryButton: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: Radius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.surface,
    paddingHorizontal: 16,
  },
  secondaryButtonText: { color: theme.inkSoft, fontSize: 14, fontWeight: '800', letterSpacing: 0.3 },
  })
}

export function createNewMatchStyles(theme: SportPalette, runTheme: RunArenaColors = RunArenaPalette, language: AppLanguage = 'en') {
  const isThai = language === 'th'
  // Rally bilingual type — mirrors lib/typography/resolveFont.ts. Thai body/head
  // fragments intentionally omit fontWeight/lineHeight: a single-face Thai family
  // (Prompt_700Bold / IBMPlexSansThai_400Regular) drops combining marks
  // (สระ/วรรณยุกต์) when either prop is present alongside it.
  const head = isThai
    ? { fontFamily: Fonts?.thaiHead, fontStyle: 'italic' as const }
    : { fontWeight: '900' as const, fontStyle: 'italic' as const }
  const body = isThai
    ? { fontFamily: Fonts?.thaiBody }
    : { fontFamily: Fonts?.rounded }
  const num = { fontFamily: Fonts?.number } // Latin/tabular numerals — safe in both languages

  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: theme.arenaPage,
    },
    scroller: {
      flex: 1,
      backgroundColor: 'transparent',
    },
    container: {
      padding: Spacing.xl,
      paddingTop: 48,
      paddingBottom: 64,
      gap: Spacing.md,
      position: 'relative',
    },
    topBar: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.md,
    },
    topBackButton: {
      width: 44,
      height: 44,
      borderRadius: Radius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.arcadePanel,
      boxShadow: theme.shadowSoft,
    },
    topTitle: {
      flex: 1,
      color: theme.arenaInk,
      fontSize: 17,
      textAlign: 'center',
      ...head,
    },
    topSpacer: {
      width: 44,
      height: 44,
    },
    runningTopBackButton: {
      backgroundColor: runTheme.surfaceRaised,
    },
    reelShell: {
      position: 'relative',
      gap: Spacing.sm,
      paddingTop: 0,
    },
    reelControls: {
      minHeight: 74,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    reelArrowButton: {
      width: 42,
      height: 58,
      borderRadius: Radius.lg,
      backgroundColor: theme.arcadeCabinet,
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: theme.shadowSoft,
    },
    runningReelArrowButton: {
      backgroundColor: runTheme.surface,
    },
    reelTrack: {
      flex: 1,
      minHeight: 76,
      position: 'relative',
      overflow: 'hidden',
    },
    reelIconSlot: {
      borderRadius: Radius.xl,
      borderWidth: 1,
      backgroundColor: theme.arcadePanel,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reelIconSlotFloating: {
      position: 'absolute',
    },
    reelIconSlotActive: {
      boxShadow: theme.shadowSoft,
    },
    reelIconSlotLocked: {
      backgroundColor: 'rgba(249,246,240,0.52)',
    },
    reelLockBadge: {
      position: 'absolute',
      right: -5,
      bottom: -5,
      width: 18,
      height: 18,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.muted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cockpitPanel: {
      borderRadius: Radius.xxl,
      borderWidth: 1,
      padding: Spacing.md,
      gap: Spacing.sm,
      boxShadow: theme.shadowSoft,
    },
    runningEntryPanel: {
      borderRadius: Radius.xxl,
      borderWidth: 0,
    },
    runningEntryRow: {
      minHeight: 106,
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: Spacing.sm,
    },
    runningEntryCard: {
      flex: 1,
      minWidth: 0,
      borderRadius: Radius.xl,
      borderWidth: 1,
      backgroundColor: 'rgba(249,246,240,0.055)',
      padding: Spacing.md,
      justifyContent: 'space-between',
      overflow: 'hidden',
    },
    runningSoloEntryCard: {
      flex: 1.22,
      backgroundColor: runTheme.surfaceRaised,
      borderColor: runTheme.primaryLine,
    },
    runningRoomEntryCard: {
      flex: 0.9,
      opacity: 0.92,
    },
    runningEntryCardActive: {
      backgroundColor: 'rgba(249,246,240,0.12)',
    },
    runningEntryCardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    runningEntryIcon: {
      width: 38,
      height: 38,
      borderRadius: Radius.lg,
      borderWidth: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    runningSoloEntryIcon: {
      backgroundColor: runTheme.primary,
      borderColor: runTheme.primaryLine,
    },
    runningEntryRoomIcon: {
      borderColor: 'rgba(249,246,240,0.16)',
      backgroundColor: 'rgba(249,246,240,0.08)',
    },
    runningEntryCopy: {
      gap: 2,
    },
    runningEntryTitle: {
      color: theme.fightInk,
      fontSize: 17,
      letterSpacing: 0,
      ...head,
    },
    runningSoloEntryTitle: {
      color: runTheme.text,
    },
    runningEntryMeta: {
      fontSize: 10,
      letterSpacing: 0.55,
      textTransform: 'uppercase',
      ...body,
    },
    cockpitHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.md,
    },
    cockpitSportBadge: {
      width: 48,
      height: 48,
      borderRadius: Radius.lg,
      borderWidth: 1,
      backgroundColor: 'rgba(249,246,240,0.08)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cockpitTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    cockpitEyebrow: {
      fontSize: 10,
      letterSpacing: 1.4,
      ...head,
    },
    cockpitTitle: {
      color: theme.fightInk,
      fontSize: 25,
      letterSpacing: 0,
      ...head,
    },
    cockpitMetaRow: {
      marginTop: 6,
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
    },
    cockpitMetaPill: {
      minHeight: 24,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.12)',
      backgroundColor: 'rgba(249,246,240,0.06)',
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    cockpitMetaText: {
      fontSize: 10,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      ...head,
    },
    cockpitAccessButton: {
      minWidth: 80,
      height: 40,
      borderRadius: Radius.lg,
      borderWidth: 1,
      backgroundColor: 'rgba(249,246,240,0.045)',
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    cockpitAccessLabel: {
      fontSize: 10,
      letterSpacing: 0.25,
      ...head,
    },
    cockpitPresetGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    cockpitPresetTile: {
      flexGrow: 1,
      flexBasis: 116,
      minHeight: 46,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.1)',
      backgroundColor: 'rgba(249,246,240,0.055)',
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
    },
    cockpitPresetValue: {
      flexShrink: 1,
      minWidth: 0,
      color: theme.fightInk,
      fontSize: 14,
      letterSpacing: 0.2,
      textTransform: 'uppercase',
      ...head,
    },
    cockpitPresetCopy: {
      flexShrink: 1,
      minWidth: 0,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    cockpitPresetMeta: {
      marginTop: -1,
      fontSize: 9,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      ...body,
    },
    cockpitControlStack: {
      gap: 8,
    },
    cockpitQuickStepperRow: {
      minHeight: 38,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.1)',
      backgroundColor: 'rgba(249,246,240,0.04)',
      paddingLeft: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      overflow: 'hidden',
    },
    cockpitQuickStepperLabel: {
      width: 44,
      fontSize: 9,
      letterSpacing: 0.35,
      textTransform: 'uppercase',
      ...head,
    },
    cockpitQuickStepperControl: {
      flex: 1,
      minWidth: 0,
      borderWidth: 0,
      backgroundColor: 'transparent',
    },
    cockpitGroup: {
      borderRadius: Radius.lg,
      borderWidth: 0,
      backgroundColor: 'transparent',
      paddingVertical: 2,
      gap: 7,
    },
    cockpitGroupHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 12,
      opacity: 0.62,
    },
    cockpitGroupTitle: {
      fontSize: 9,
      letterSpacing: 0.2,
      ...head,
    },
    cockpitChipRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    cockpitChoiceRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 7,
    },
    cockpitChoice: {
      flexGrow: 1,
      flexBasis: 86,
    },
    cockpitChip: {
      minHeight: 34,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.09)',
      backgroundColor: 'rgba(249,246,240,0.04)',
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    cockpitChipText: {
      color: 'rgba(249,246,240,0.82)',
      fontSize: 11,
      letterSpacing: 0.15,
      ...head,
    },
    cockpitStepper: {
      minHeight: 34,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.1)',
      backgroundColor: 'rgba(249,246,240,0.04)',
      flexDirection: 'row',
      alignItems: 'center',
      overflow: 'hidden',
    },
    cockpitStepperWide: {
      alignSelf: 'stretch',
      justifyContent: 'space-between',
    },
    cockpitStepperButton: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cockpitStepperValue: {
      minWidth: 36,
      color: theme.fightInk,
      fontSize: 15,
      lineHeight: 19,
      fontWeight: '900',
      textAlign: 'center',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    cockpitStepperValueWide: {
      flex: 1,
      minWidth: 0,
    },
    cockpitStakeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    cockpitStakeChoiceRow: {
      flex: 1,
      minWidth: 0,
    },
    cockpitStakeHeaderRow: {
      minHeight: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.sm,
    },
    cockpitStakeHeaderMeta: {
      fontSize: 9,
      letterSpacing: 0,
      ...head,
    },
    cockpitStakeWalletCard: {
      minHeight: 46,
      borderRadius: Radius.lg,
      borderWidth: 0,
      backgroundColor: 'rgba(249,246,240,0.062)',
      paddingVertical: 6,
      paddingHorizontal: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: Spacing.md,
    },
    cockpitStakeWalletCopy: {
      flex: 1,
      minWidth: 0,
    },
    cockpitStakeWalletLabel: {
      fontSize: 9,
      letterSpacing: 0.2,
      opacity: 0.78,
      ...head,
    },
    cockpitStakeWalletValueRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 7,
      marginTop: 1,
    },
    cockpitStakeWalletValue: {
      color: theme.fightInk,
      fontSize: 24,
      lineHeight: 27,
      fontWeight: '900',
      letterSpacing: 0,
      fontVariant: ['tabular-nums'],
      ...num,
    },
    cockpitStakeWalletUnit: {
      fontSize: 10,
      letterSpacing: 0.65,
      opacity: 0.82,
      ...head,
    },
    cockpitStakeWalletIcon: {
      width: 30,
      height: 30,
      borderRadius: Radius.md,
      borderWidth: 0,
      backgroundColor: 'rgba(10,14,11,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cockpitStakePicker: {
      gap: 8,
    },
    cockpitStakeQuickRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    cockpitStakeQuickChip: {
      flexGrow: 1,
      flexBasis: 68,
      minHeight: 38,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.1)',
      backgroundColor: 'rgba(249,246,240,0.045)',
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
    },
    cockpitStakeQuickText: {
      color: theme.fightInk,
      fontSize: 15,
      lineHeight: 19,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    cockpitStakeQuickUnit: {
      color: theme.fightMuted,
      fontSize: 9,
      letterSpacing: 0.5,
      ...head,
    },
    cockpitStakeDirectRow: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    cockpitStakeStepButton: {
      width: 44,
      height: 44,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.1)',
      backgroundColor: 'rgba(249,246,240,0.055)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    cockpitStakeDirectInputShell: {
      flex: 1,
      minWidth: 0,
      minHeight: 44,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.1)',
      backgroundColor: 'rgba(10,14,11,0.28)',
      paddingLeft: Spacing.md,
      paddingRight: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    cockpitStakeDirectInput: {
      minWidth: 48,
      minHeight: 40,
      color: theme.economy,
      textAlign: 'center',
      fontSize: 20,
      lineHeight: 24,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    cockpitStakeAmountShellRisk: {
      borderColor: theme.risk,
      backgroundColor: theme.riskSoft,
    },
    cockpitStakeInputRisk: {
      color: theme.risk,
    },
    cockpitStakeUnit: {
      color: theme.fightMuted,
      fontSize: 10,
      letterSpacing: 0.9,
      ...head,
    },
    cockpitStakeUnitRisk: {
      color: theme.risk,
    },
    cockpitLockRow: {
      alignSelf: 'flex-start',
      minHeight: 38,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.2)',
      backgroundColor: 'rgba(249,246,240,0.08)',
      paddingHorizontal: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    cockpitCodeInput: {
      minHeight: 44,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.24)',
      backgroundColor: 'rgba(10,14,11,0.34)',
      color: theme.fightInk,
      paddingHorizontal: Spacing.md,
      textAlign: 'center',
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '900',
      letterSpacing: 6,
      fontVariant: ['tabular-nums'],
      ...num,
    },
    cockpitInlineCodeRow: {
      minHeight: 42,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.24)',
      backgroundColor: 'rgba(249,246,240,0.08)',
      paddingHorizontal: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    cockpitInlineCodeInput: {
      flex: 1,
      minWidth: 0,
      minHeight: 40,
      color: theme.fightInk,
      textAlign: 'center',
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '900',
      letterSpacing: 6,
      fontVariant: ['tabular-nums'],
      ...num,
    },
    cockpitOpenRoomButton: {
      minHeight: 62,
      marginTop: 2,
    },
    floorPreview: {
      position: 'relative',
      minHeight: 292,
      borderRadius: Radius.xxl,
      borderWidth: 1,
      padding: Spacing.md,
      overflow: 'hidden',
      justifyContent: 'space-between',
    },
    floorPreviewLocked: {
      opacity: 0.74,
    },
    floorHudRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: Spacing.md,
    },
    floorScoreBlock: {
      flex: 1,
      minWidth: 0,
    },
    floorEyebrow: {
      fontSize: 10,
      letterSpacing: 1.4,
      ...head,
    },
    floorScoreRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: Spacing.xs,
      marginTop: 2,
    },
    floorScore: {
      color: theme.fightInk,
      fontSize: 48,
      lineHeight: 52,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      letterSpacing: 0,
      ...num,
    },
    floorScoreUnit: {
      color: theme.fightMuted,
      fontSize: 12,
      letterSpacing: 1.1,
      ...head,
    },
    floorSportBadge: {
      width: 42,
      height: 42,
      borderRadius: Radius.md,
      borderWidth: 1,
      backgroundColor: 'rgba(249,246,240,0.08)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    floorSelfRow: {
      minHeight: 54,
      borderRadius: Radius.lg,
      borderWidth: 1,
      backgroundColor: 'rgba(249,246,240,0.1)',
      padding: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    floorSelfRank: {
      minWidth: 42,
      height: 36,
      borderRadius: Radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.sm,
    },
    floorSelfRankText: {
      color: theme.onEconomy,
      fontSize: 10,
      letterSpacing: 0.8,
      ...head,
    },
    floorSelfAvatar: {
      width: 34,
      height: 34,
      borderRadius: Radius.pill,
      backgroundColor: 'rgba(249,246,240,0.86)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    floorSelfAvatarText: {
      color: theme.fightPanel,
      fontSize: 15,
      ...head,
    },
    floorSelfCopy: {
      flex: 1,
      minWidth: 0,
    },
    floorSelfName: {
      color: theme.fightInk,
      fontSize: 14,
      ...head,
    },
    floorSelfMeta: {
      marginTop: 1,
      fontSize: 9,
      letterSpacing: 0.7,
      ...body,
    },
    floorSelfScoreVault: {
      minWidth: 70,
      height: 34,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.22)',
      backgroundColor: 'rgba(10,14,11,0.48)',
      paddingHorizontal: Spacing.sm,
      alignItems: 'flex-end',
      justifyContent: 'center',
    },
    floorSelfScore: {
      fontSize: 17,
      lineHeight: 20,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    floorHistoryRow: {
      gap: 6,
    },
    floorHistoryItem: {
      minHeight: 40,
      borderRadius: Radius.lg,
      borderWidth: 1,
      backgroundColor: 'rgba(249,246,240,0.08)',
      paddingVertical: 6,
      paddingHorizontal: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    floorHistoryResultBadge: {
      width: 24,
      height: 24,
      borderRadius: Radius.sm,
      borderWidth: 1,
      backgroundColor: 'rgba(249,246,240,0.06)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    floorHistoryResult: {
      fontSize: 9,
      letterSpacing: 0.8,
      ...head,
    },
    floorHistoryTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    floorHistoryScore: {
      color: theme.fightInk,
      fontSize: 13,
      lineHeight: 16,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    floorHistoryMeta: {
      fontSize: 9,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
      ...body,
    },
    floorHistoryDelta: {
      color: theme.fightInk,
      fontSize: 14,
      lineHeight: 17,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    sportGrid: {
      gap: Spacing.md,
    },
    sportCard: {
      minHeight: 112,
      borderRadius: Radius.xxl,
      borderWidth: 1,
      padding: Spacing.lg,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      backgroundColor: theme.arcadePanel,
      boxShadow: theme.shadowSoft,
    },
    sportCardIcon: {
      width: 58,
      height: 58,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: theme.line,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sportCardTitle: {
      flex: 1,
      minWidth: 0,
      color: theme.ink,
      fontSize: 24,
      letterSpacing: 0,
      ...head,
    },
    heroCard: {
      borderWidth: 1,
      borderColor: theme.line,
      borderRadius: Radius.xxl,
      backgroundColor: theme.arcadeCabinet,
      padding: Spacing.lg,
      gap: Spacing.md,
      overflow: 'hidden',
      boxShadow: theme.shadowSoft,
    },
    heroSurface: {
      position: 'absolute',
      left: 6,
      right: 6,
      top: 6,
      bottom: 6,
      borderRadius: Radius.xxl - 7,
      borderWidth: 1,
      borderColor: theme.economy,
      backgroundColor: theme.fightPanel,
    },
    heroTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
    },
    heroIcon: {
      width: 48,
      height: 48,
      borderRadius: Radius.lg,
      backgroundColor: theme.economy,
      borderWidth: 1,
      borderColor: theme.economy,
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroCopy: {
      flex: 1,
      minWidth: 0,
    },
    heroEyebrow: {
      color: theme.economy,
      fontSize: 10,
      letterSpacing: 1.6,
      ...head,
    },
    heroTitle: {
      color: theme.fightInk,
      fontSize: 26,
      letterSpacing: 0,
      ...head,
    },
    setupMeter: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
    },
    setupStepWrap: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
    },
    setupNode: {
      width: 36,
      height: 36,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: theme.fightLine,
      backgroundColor: theme.arcadeChip,
      alignItems: 'center',
      justifyContent: 'center',
    },
    setupNodeReady: {
      borderColor: theme.economy,
      backgroundColor: theme.economy,
    },
    setupConnector: {
      flex: 1,
      height: 3,
      marginHorizontal: 5,
      borderRadius: Radius.pill,
      backgroundColor: theme.arcadeChip,
    },
    setupConnectorReady: {
      backgroundColor: theme.economy,
    },
    heroStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      flexWrap: 'wrap',
    },
    heroStatusPill: {
      minHeight: 30,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: theme.fightLine,
      backgroundColor: theme.arcadeChip,
      paddingHorizontal: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    heroStatusText: {
      fontSize: 11,
      letterSpacing: 0.6,
      ...head,
    },
    sectionPanel: {
      borderWidth: 1,
      borderColor: theme.line,
      borderRadius: Radius.xxl,
      backgroundColor: theme.arcadePanel,
      padding: Spacing.lg,
      gap: Spacing.md,
      boxShadow: theme.shadowSoft,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    sectionNumber: {
      width: 32,
      height: 32,
      borderRadius: Radius.pill,
      backgroundColor: theme.orange,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sectionNumberText: {
      color: theme.arcadeCtaText,
      fontSize: 11,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    sectionCopy: {
      flex: 1,
      minWidth: 0,
    },
    sectionTitle: {
      color: theme.ink,
      fontSize: 17,
      letterSpacing: 0,
      ...head,
    },
    sectionHint: {
      color: theme.muted,
      fontSize: 12,
      ...body,
    },
    soloRunCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.md,
      padding: Spacing.lg,
      borderRadius: Radius.xl,
      backgroundColor: theme.arcadePanel,
      boxShadow: theme.shadowSoft,
    },
    soloRunIcon: {
      width: 40,
      height: 40,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.orange,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.orangeSoft,
    },
    soloRunTitle: {
      fontSize: 15,
      color: theme.ink,
      ...head,
    },
    soloRunHint: {
      fontSize: 12,
      color: theme.muted,
      marginTop: 2,
      ...body,
    },
    soloRunBadges: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
      marginTop: Spacing.xs,
    },
    soloRunBadge: {
      minHeight: 24,
      overflow: 'hidden',
      borderRadius: Radius.pill,
      backgroundColor: theme.orangeSoft,
      borderWidth: 1,
      borderColor: theme.orange,
      color: theme.orange,
      paddingHorizontal: Spacing.sm,
      paddingTop: 4,
      fontSize: 10,
      letterSpacing: 0.6,
      ...head,
    },
    label: {
      fontSize: 10,
      color: theme.trust,
      letterSpacing: 1.4,
      textTransform: 'uppercase',
      ...head,
    },
    hint: { fontSize: 12, color: theme.mutedSoft, marginTop: 4, ...body },
    pills: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
    optionRow: { flexDirection: 'row', gap: Spacing.sm },
    optionPill: {
      flex: 1,
      minWidth: 0,
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    optionStack: { gap: Spacing.sm },
    optionCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.sm,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      borderRadius: Radius.lg,
      padding: Spacing.md,
      backgroundColor: theme.arcadePanelAlt,
    },
    optionCardActive: {
      backgroundColor: theme.orangeSoft,
      borderColor: theme.orange,
    },
    optionTitle: { fontSize: 14, color: theme.ink, letterSpacing: 0, ...head },
    optionHint: { fontSize: 12, color: theme.muted, marginTop: 2, ...body },
    optionMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 7 },
    optionMetaPill: {
      overflow: 'hidden',
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: Radius.pill,
      backgroundColor: theme.surfaceStrong,
      color: theme.inkSoft,
      fontSize: 10,
      ...head,
    },
    modeHint: {
      fontSize: 12,
      color: theme.muted,
      ...body,
    },
    modeSignal: {
      alignSelf: 'flex-start',
      maxWidth: '100%',
      minHeight: 30,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: theme.trust,
      backgroundColor: theme.trustSoft,
      paddingHorizontal: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    modeSignalText: {
      flexShrink: 1,
      color: theme.trust,
      fontSize: 11,
      ...body,
    },
    pill: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      borderRadius: Radius.pill,
      paddingVertical: 9,
      paddingHorizontal: 14,
      backgroundColor: theme.arcadePanelAlt,
    },
    pillActive: {
      backgroundColor: theme.orangeSoft,
      borderColor: theme.orange,
    },
    pillText: { fontSize: 13, color: theme.inkSoft, letterSpacing: 0.2, ...head },
    optionPillText: { flexShrink: 1, minWidth: 0 },
    pillTextActive: { color: theme.orange },
    stepper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    stepperButton: {
      width: 44,
      height: 44,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.arcadePanelAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperButtonDisabled: {
      opacity: 0.45,
      borderColor: theme.lineStrong,
      backgroundColor: theme.surface,
    },
    stepperValue: {
      flex: 1,
      minHeight: 44,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      backgroundColor: theme.arcadePanelAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperNumber: {
      fontSize: 24,
      fontWeight: '900',
      color: theme.ink,
      fontVariant: ['tabular-nums'],
      lineHeight: 28,
      ...num,
    },
    stepperLabel: { fontSize: 10, color: theme.trust, letterSpacing: 1.2, ...head },
    input: {
      minHeight: 48,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      borderRadius: Radius.lg,
      padding: 14,
      fontSize: 15,
      color: theme.ink,
      backgroundColor: theme.arcadePanelAlt,
      ...body,
    },
    codeInput: {
      letterSpacing: 6,
      textAlign: 'center',
      marginTop: Spacing.sm,
      ...head,
    },
    inviteeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    sideBadge: {
      minWidth: 64,
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: Radius.sm,
      backgroundColor: theme.surfaceStrong,
      color: theme.inkSoft,
      fontSize: 10,
      letterSpacing: 0,
      textAlign: 'center',
      ...head,
    },
    inviteePicker: {
      flex: 1,
      minWidth: 0,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      borderRadius: Radius.lg,
      paddingHorizontal: Spacing.md,
      backgroundColor: theme.arcadePanelAlt,
    },
    inviteePickerActive: {
      borderColor: theme.orange,
      backgroundColor: theme.orangeSoft,
    },
    inviteePickerText: {
      flex: 1,
      minWidth: 0,
      color: theme.muted,
      fontSize: 13,
      ...body,
    },
    inviteePickerTextActive: {
      color: theme.orange,
      ...body,
    },
    clearInviteeButton: {
      width: 40,
      height: 40,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      backgroundColor: theme.arcadePanelAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    lobbyRow: { flexDirection: 'row', gap: Spacing.sm },
    duelPreview: {
      minHeight: 72,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.arcadePanelAlt,
      padding: Spacing.md,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.md,
    },
    duelSide: {
      width: 46,
      height: 46,
      borderRadius: Radius.pill,
      backgroundColor: theme.orange,
      alignItems: 'center',
      justifyContent: 'center',
    },
    duelSidePending: {
      backgroundColor: theme.surfaceStrong,
      borderColor: theme.lineStrong,
    },
    duelVs: {
      color: theme.ink,
      fontSize: 18,
      letterSpacing: 1,
      ...head,
    },
    lobbyChip: {
      flex: 1,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingVertical: 11,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      backgroundColor: theme.arcadePanelAlt,
    },
    lobbyChipActive: {
      backgroundColor: theme.orangeSoft,
      borderColor: theme.orange,
    },
    lobbyChipText: { fontSize: 13, color: theme.muted, ...head },
    lockRow: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 11,
      paddingHorizontal: 14,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      backgroundColor: theme.arcadePanelAlt,
    },
    lockRowActive: {
      borderColor: theme.economy,
      backgroundColor: theme.economySoft,
    },
    lockRowText: { flex: 1, fontSize: 13, color: theme.muted, ...head },
    // Thai label (เปิดให้ดูสด) — no fontWeight/lineHeight, see usage site.
    spectateRowText: { flex: 1, fontSize: 13, color: theme.muted, ...body },
    stakeCard: {
      borderWidth: 1,
      borderColor: theme.fightLine,
      borderRadius: Radius.xl,
      backgroundColor: theme.fightPanel,
      padding: Spacing.md,
      gap: Spacing.md,
    },
    stakeRow: { flexDirection: 'row', gap: Spacing.sm },
    stakeAmountInput: {
      minHeight: 58,
      borderWidth: 1,
      borderColor: theme.fightLine,
      backgroundColor: theme.arcadeCabinet,
      color: theme.economy,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '900',
      textAlign: 'center',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    stakeUnit: {
      fontSize: 11,
      color: theme.fightMuted,
      letterSpacing: 0.3,
      textAlign: 'center',
      ...body,
    },
    consentCard: {
      minHeight: 52,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.trust,
      backgroundColor: theme.trustSoft,
      padding: Spacing.md,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: Spacing.sm,
    },
    consentText: {
      flex: 1,
      minWidth: 0,
      color: theme.ink,
      fontSize: 12,
      ...body,
    },
    readyGrid: {
      minHeight: 64,
      borderRadius: Radius.xl,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.arcadePanelAlt,
      padding: Spacing.sm,
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    readyTile: {
      flex: 1,
      minHeight: 48,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      backgroundColor: theme.surface,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
    },
    readyTileActive: {
      borderColor: theme.trust,
      backgroundColor: theme.trustSoft,
    },
    readyTileText: {
      color: theme.trust,
      fontSize: 11,
      letterSpacing: 0.8,
      ...head,
    },
    readyTileTextMuted: {
      color: theme.muted,
      fontSize: 11,
      letterSpacing: 0.8,
      ...head,
    },
    readyVs: {
      width: 32,
      height: 32,
      borderRadius: Radius.pill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.arcadePanel,
      borderWidth: 1,
      borderColor: theme.lineStrong,
    },
    stakeDialogBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(8,10,8,0.72)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.xl,
    },
    stakeDialogCard: {
      width: '100%',
      maxWidth: 340,
      borderRadius: Radius.xl,
      borderWidth: 1,
      padding: Spacing.lg,
      gap: Spacing.md,
      boxShadow: theme.shadowSoft,
    },
    stakeDialogHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Spacing.sm,
    },
    stakeDialogTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    stakeDialogTitle: {
      color: theme.fightInk,
      fontSize: 22,
      letterSpacing: 0,
      ...head,
    },
    stakeDialogSubtitle: {
      marginTop: 1,
      fontSize: 10,
      letterSpacing: 0.7,
      textTransform: 'uppercase',
      ...body,
    },
    stakeDialogClose: {
      width: 34,
      height: 34,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.12)',
      backgroundColor: 'rgba(249,246,240,0.06)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    stakeDialogDisplayCard: {
      minHeight: 94,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.13)',
      backgroundColor: 'rgba(249,246,240,0.075)',
      paddingVertical: Spacing.md,
      paddingHorizontal: Spacing.md,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 2,
    },
    stakeDialogDisplayLabel: {
      color: theme.fightMuted,
      fontSize: 10,
      letterSpacing: 2,
      ...head,
    },
    stakeDialogDisplayValue: {
      color: theme.fightInk,
      fontSize: 48,
      lineHeight: 54,
      fontWeight: '900',
      letterSpacing: 0,
      fontVariant: ['tabular-nums'],
      ...num,
    },
    stakeDialogDisplayValueEmpty: {
      color: theme.fightMuted,
    },
    stakeDialogDisplayValueRisk: {
      color: theme.risk,
    },
    stakeDialogDisplayUnit: {
      color: theme.fightMuted,
      fontSize: 10,
      letterSpacing: 1.4,
      ...head,
    },
    stakeDialogQuickRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
    },
    stakeDialogQuickChip: {
      flex: 1,
      minHeight: 36,
      borderRadius: Radius.pill,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.13)',
      backgroundColor: 'rgba(249,246,240,0.075)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.sm,
    },
    stakeDialogQuickChipSelected: {
      borderColor: theme.economy,
      backgroundColor: theme.economy,
    },
    stakeDialogQuickText: {
      color: theme.fightInk,
      fontSize: 13,
      lineHeight: 17,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    stakeDialogQuickTextSelected: {
      color: theme.onEconomy,
    },
    stakeDialogHint: {
      color: theme.fightMuted,
      fontSize: 11,
      textAlign: 'center',
      ...body,
    },
    stakeDialogHintRisk: {
      color: theme.risk,
      ...body,
    },
    stakeDialogKeypad: {
      gap: 7,
    },
    stakeDialogKeypadRow: {
      flexDirection: 'row',
      gap: 7,
    },
    stakeDialogKey: {
      flex: 1,
      minHeight: 39,
      borderRadius: Radius.md,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.13)',
      backgroundColor: 'rgba(249,246,240,0.115)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    stakeDialogKeyMuted: {
      backgroundColor: 'rgba(249,246,240,0.055)',
    },
    stakeDialogKeyDisabled: {
      opacity: 0.4,
    },
    stakeDialogKeyText: {
      color: theme.fightInk,
      fontSize: 22,
      lineHeight: 27,
      fontWeight: '900',
      fontVariant: ['tabular-nums'],
      ...num,
    },
    stakeDialogKeyMutedText: {
      color: theme.fightMuted,
      fontSize: 18,
      letterSpacing: 1.2,
      ...head,
    },
    stakeDialogActions: {
      flexDirection: 'row',
      gap: Spacing.sm,
    },
    stakeDialogSecondaryButton: {
      flex: 1,
      minHeight: 46,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: 'rgba(249,246,240,0.12)',
      backgroundColor: 'rgba(249,246,240,0.045)',
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.md,
    },
    stakeDialogSecondaryText: {
      color: theme.fightInk,
      fontSize: 12,
      letterSpacing: 0.8,
      ...head,
    },
    stakeDialogPrimaryButton: {
      flex: 1,
      minHeight: 46,
      borderRadius: Radius.lg,
      borderWidth: 1,
      borderColor: theme.line,
      backgroundColor: theme.economy,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: Spacing.md,
    },
    stakeDialogPrimaryButtonDisabled: {
      opacity: 0.48,
    },
    stakeDialogPrimaryText: {
      color: theme.onEconomy,
      fontSize: 14,
      letterSpacing: 0.8,
      ...head,
    },
    button: {
      minHeight: Arcade.cta.height,
      backgroundColor: theme.economy,
      borderRadius: Arcade.cta.radius,
      paddingHorizontal: Spacing.lg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: Spacing.sm,
      boxShadow: theme.shadowSoft,
    },
    buttonText: { color: theme.onEconomy, fontSize: 15, letterSpacing: 0.5, ...head },
    secondaryButton: {
      minHeight: 48,
      borderWidth: 1,
      borderColor: theme.lineStrong,
      borderRadius: Radius.lg,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.arcadePanelAlt,
      paddingHorizontal: 16,
    },
    secondaryButtonText: { color: theme.inkSoft, fontSize: 14, letterSpacing: 0.3, ...head },
  })
}
