import { Platform, StyleSheet } from 'react-native'

import { Radius, Spacing } from '@/constants/theme'

export const RunningMapLobbyArena = {
  base: '#f4f5ee',
  surface: '#f7f8f3',
  surfaceRaised: '#fbfcf8',
  text: '#161616',
  muted: '#7b8179',
  mutedStrong: '#424947',
  accent: '#d9ff4f',
  accentSoft: 'rgba(217,255,79,0.28)',
  economy: '#eac31a',
  trust: '#0fa968',
  trustSoft: 'rgba(15,169,104,0.12)',
  warning: '#d9a441',
  danger: '#c73f41',
  dangerSoft: 'rgba(199,63,65,0.12)',
  codeText: 'rgba(22,22,22,0.34)',
  border: 'rgba(92,108,62,0.18)',
  borderStrong: 'rgba(92,108,62,0.28)',
  shadow: 'rgba(71,88,111,0.2)',
  mapTint: 'rgba(247,248,243,0.1)',
} as const

const Arena = RunningMapLobbyArena

export const runningMapLobbyStageStyles = StyleSheet.create({
  stage: {
    marginHorizontal: -14,
    overflow: 'hidden',
    backgroundColor: Arena.base,
  },
  mapShell: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 0,
    overflow: 'hidden',
    borderWidth: 0,
    borderColor: 'transparent',
    backgroundColor: Arena.base,
    ...Platform.select({
      web: { boxShadow: `0 18px 36px ${Arena.shadow}` },
      default: {
        shadowColor: Arena.text,
        shadowOffset: { width: 0, height: 16 },
        shadowOpacity: 0.14,
        shadowRadius: 28,
        elevation: 8,
      },
    }),
  },
  mapMist: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Arena.mapTint,
  },
  floatingHeader: {
    position: 'absolute',
    left: 18,
    right: 18,
    minHeight: 64,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    backgroundColor: 'rgba(251,252,248,0.95)',
    paddingLeft: 14,
    paddingRight: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    ...Platform.select({
      web: { boxShadow: `0 10px 24px ${Arena.shadow}` },
      default: {
        shadowColor: Arena.text,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.1,
        shadowRadius: 18,
        elevation: 4,
      },
    }),
  },
  headerBack: {
    width: 38,
    height: 38,
    borderRadius: 12,
  },
  headerTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  headerRightRail: {
    alignItems: 'flex-end',
    justifyContent: 'center',
    gap: 4,
  },
  heroSport: {
    color: Arena.muted,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
    letterSpacing: 0.8,
  },
  heroTitle: {
    color: Arena.text,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '900',
    letterSpacing: 0,
  },
  miniChip: {
    minHeight: 25,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(22,22,22,0.08)',
    backgroundColor: 'rgba(247,248,243,0.96)',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  miniChipText: {
    color: Arena.text,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  codeChip: {
    minHeight: 22,
    maxWidth: 104,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(22,22,22,0.05)',
    backgroundColor: 'rgba(247,248,243,0.56)',
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  codeText: {
    color: Arena.codeText,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
    fontVariant: ['tabular-nums'],
  },
  mapModeChip: {
    position: 'absolute',
    top: 78,
    left: 18,
    maxWidth: '72%',
    minHeight: 28,
    borderRadius: Radius.pill,
    backgroundColor: 'rgba(251,252,248,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    paddingHorizontal: 11,
    justifyContent: 'center',
  },
  mapModeText: {
    color: Arena.mutedStrong,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '900',
  },
  mapStatusRail: {
    position: 'absolute',
    left: 12,
    right: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  gpsStatusChip: {
    minHeight: 34,
    minWidth: 48,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(15,169,104,0.16)',
    backgroundColor: 'rgba(251,252,248,0.86)',
    paddingHorizontal: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  gpsStatusChipQuiet: {
    minWidth: 38,
    width: 38,
    borderColor: 'rgba(15,169,104,0.16)',
    backgroundColor: 'rgba(251,252,248,0.92)',
  },
  gpsStatusChipDanger: {
    borderColor: 'rgba(199,63,65,0.34)',
  },
  gpsStatusText: {
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  liveStatChip: {
    flex: 1,
    minHeight: 34,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(22,22,22,0.09)',
    backgroundColor: Arena.accent,
    paddingHorizontal: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  liveStatChipPoints: {
    flex: 1.12,
    borderColor: 'rgba(22,22,22,0.07)',
    backgroundColor: 'rgba(251,252,248,0.92)',
  },
  liveStatLabel: {
    color: Arena.text,
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
  },
  liveStatLabelPoints: {
    color: Arena.muted,
  },
  liveStatValue: {
    color: Arena.text,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  liveStatValuePoints: {
    color: Arena.text,
  },
  slot: {
    position: 'absolute',
    width: 66,
    minHeight: 66,
    marginLeft: -33,
    marginTop: -33,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(22,22,22,0.12)',
    backgroundColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
    paddingVertical: 6,
    ...Platform.select({
      web: { boxShadow: `0 10px 20px ${Arena.shadow}` },
      default: {
        shadowColor: Arena.text,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.14,
        shadowRadius: 16,
        elevation: 5,
      },
    }),
  },
  slotOccupied: {
    width: 82,
    minHeight: 82,
    marginLeft: -41,
    marginTop: -41,
    borderRadius: 26,
    borderColor: Arena.accent,
    backgroundColor: 'rgba(15,169,104,0.92)',
  },
  slotPending: {
    borderColor: Arena.warning,
    backgroundColor: 'rgba(255,255,255,0.94)',
  },
  slotAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(22,22,22,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(22,22,22,0.08)',
  },
  slotAvatarOccupied: {
    backgroundColor: Arena.surfaceRaised,
    borderColor: 'rgba(255,255,255,0.76)',
  },
  slotInitials: {
    color: Arena.mutedStrong,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '900',
  },
  slotInitialsOccupied: {
    color: Arena.text,
  },
  slotTextBlock: {
    width: '100%',
    minWidth: 0,
    alignItems: 'center',
    marginTop: 5,
  },
  slotName: {
    maxWidth: '100%',
    color: Arena.surfaceRaised,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '900',
  },
  slotMeta: {
    marginTop: 1,
    color: 'rgba(255,255,255,0.78)',
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  slotMetaOpen: {
    marginTop: 3,
    color: Arena.mutedStrong,
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
    letterSpacing: 0.7,
  },
  refSlotName: {
    maxWidth: '100%',
    color: Arena.text,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '900',
  },
  refSlotMeta: {
    marginTop: 1,
    color: Arena.muted,
    fontSize: 8,
    lineHeight: 10,
    fontWeight: '900',
    letterSpacing: 0.6,
  },
  refSlot: {
    position: 'absolute',
    width: 108,
    minHeight: 50,
    marginLeft: -54,
    marginTop: -25,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: 'rgba(15,169,104,0.26)',
    backgroundColor: 'rgba(255,255,255,0.92)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    paddingHorizontal: 9,
  },
  refSlotAssigned: {
    borderColor: Arena.trust,
  },
  refSlotDisabled: {
    opacity: 0.9,
  },
  refIcon: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Arena.trustSoft,
  },
  bottomRail: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.72)',
    backgroundColor: 'rgba(251,252,248,0.97)',
    padding: 10,
    gap: 8,
    maxHeight: 310,
    ...Platform.select({
      web: { boxShadow: `0 16px 34px ${Arena.shadow}` },
      default: {
        shadowColor: Arena.text,
        shadowOffset: { width: 0, height: 14 },
        shadowOpacity: 0.13,
        shadowRadius: 24,
        elevation: 9,
      },
    }),
  },
  bottomRailCollapsed: {
    maxHeight: 154,
  },
  sheetGestureZone: {
    minHeight: 66,
    gap: 4,
  },
  sheetHandleTap: {
    minHeight: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetHandleRow: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(22,22,22,0.14)',
    marginTop: 0,
  },
  rosterHeader: {
    minHeight: 38,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  rosterTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  rosterTitle: {
    color: Arena.text,
    fontSize: 14,
    lineHeight: 17,
    fontWeight: '900',
    letterSpacing: 0,
  },
  rosterMeta: {
    marginTop: 2,
    color: Arena.muted,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '800',
  },
  rosterLivePill: {
    minHeight: 28,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(15,169,104,0.14)',
    backgroundColor: Arena.trustSoft,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  rosterLiveText: {
    color: Arena.trust,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  rosterList: {
    maxHeight: 132,
  },
  rosterListContent: {
    gap: 7,
    paddingBottom: 2,
  },
  rosterRow: {
    minHeight: 56,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: Arena.border,
    backgroundColor: 'rgba(255,255,255,0.74)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  rosterRowOccupied: {
    backgroundColor: Arena.surfaceRaised,
    borderColor: 'rgba(15,169,104,0.16)',
  },
  rosterRowDisabled: {
    opacity: 0.78,
  },
  rosterAvatarWrap: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rosterAvatarFallback: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(22,22,22,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(22,22,22,0.08)',
  },
  rosterAvatarPending: {
    backgroundColor: 'rgba(217,164,65,0.12)',
    borderColor: 'rgba(217,164,65,0.24)',
  },
  rosterAvatarText: {
    color: Arena.mutedStrong,
    fontSize: 11,
    lineHeight: 13,
    fontWeight: '900',
  },
  rosterCopy: {
    flex: 1,
    minWidth: 0,
  },
  rosterNameRow: {
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  rosterName: {
    minWidth: 0,
    color: Arena.text,
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '900',
    letterSpacing: 0,
  },
  rosterRole: {
    marginTop: 2,
    color: Arena.muted,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '800',
  },
  rosterStatusPill: {
    minHeight: 24,
    minWidth: 58,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Arena.border,
    backgroundColor: 'rgba(22,22,22,0.04)',
    paddingHorizontal: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rosterStatusLive: {
    borderColor: 'rgba(15,169,104,0.2)',
    backgroundColor: Arena.trustSoft,
  },
  rosterStatusQuiet: {
    backgroundColor: 'rgba(22,22,22,0.03)',
  },
  rosterStatusText: {
    color: Arena.mutedStrong,
    fontSize: 9,
    lineHeight: 11,
    fontWeight: '900',
    letterSpacing: 0.45,
  },
  rosterStatusTextLive: {
    color: Arena.trust,
  },
  refRosterRow: {
    borderStyle: 'dashed',
  },
  refRosterAssigned: {
    borderStyle: 'solid',
    borderColor: 'rgba(15,169,104,0.22)',
    backgroundColor: 'rgba(15,169,104,0.08)',
  },
  refRosterPending: {
    borderStyle: 'solid',
    borderColor: 'rgba(217,164,65,0.35)',
    backgroundColor: 'rgba(217,164,65,0.10)',
  },
  sheetMetaRow: {
    flexDirection: 'row',
    gap: 8,
  },
  sheetMetric: {
    flex: 1,
    minHeight: 34,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Arena.border,
    backgroundColor: Arena.surfaceRaised,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sheetMetricLabel: {
    color: Arena.muted,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '800',
  },
  sheetMetricValue: {
    color: Arena.text,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '900',
    fontVariant: ['tabular-nums'],
  },
  primaryActionDock: {
    flexDirection: 'row',
    gap: Spacing.sm,
  },
  secondaryRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  actionButton: {
    minHeight: 44,
    minWidth: 96,
    flex: 1,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: Arena.border,
    backgroundColor: Arena.surfaceRaised,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingHorizontal: 12,
  },
  actionButtonPrimary: {
    flex: 1.35,
    borderColor: Arena.accent,
    backgroundColor: Arena.accent,
  },
  actionButtonSidecar: {
    flex: 0.8,
  },
  actionButtonDanger: {
    borderColor: 'rgba(199,63,65,0.26)',
    backgroundColor: Arena.dangerSoft,
  },
  actionButtonDisabled: {
    opacity: 0.54,
  },
  actionButtonText: {
    color: Arena.text,
    fontSize: 12,
    lineHeight: 15,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  actionButtonTextPrimary: {
    color: Arena.text,
  },
  actionButtonTextDanger: {
    color: Arena.danger,
  },
  cancelLink: {
    alignSelf: 'center',
    minHeight: 30,
    borderRadius: Radius.pill,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cancelLinkText: {
    color: Arena.danger,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
})
